stages:
  - hello

hello:
  stage: hello
  script:
    - echo "Hello World"

include:
  - local: gitlab/ci.prod.yml
    rules:
      - changes:
          - .gitlab/**/**.md
        when: never
      - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
        when: never
      - if: '$CI_PIPELINE_SOURCE == "web" || $CI_JOB_MANUAL == "true"'
      - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"'
        when: always
  - local: gitlab/ci.dev.yml
    rules:
      - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
        when: never
      - if: '$CI_COMMIT_REF_NAME == "dev"'
        when: always