apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-sae5-x21
  namespace: ns-sae5-x21
  labels:
    component: nginx
spec:
  type: ClusterIP
  selector:
    component: nginx
  ports:
    - port: 80
      targetPort: 80
