apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-database-sae5-x21
  namespace: ns-sae5-x21
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - name: db-sae5-x21
          image: forge-registry.iut-larochelle.fr/mariadb/mariadb-10.10.2
          env:
            - name: MYSQL_DATABASE
              value: $MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              value: $MYSQL_USER
            - name: MYSQL_PASSWORD
              value: $MYSQL_PASSWORD
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: gitlab-auth

