apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx-sae5-x21
  namespace: ns-sae5-x21
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx-sae5-x21
          image: $CI_REGISTRY/$CI_PROJET/nginx
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gitlab-auth

