apiVersion: v1
kind: Service
metadata:
  name: svc-api-sae5-x21
  namespace: ns-sae5-x21
  labels:
    component: api
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 80
      targetPort: 8000
